name: apiverve_coordinatesaresea
description: Coordinates are Sea is a simple tool for checking if coordinates are in the sea. It returns if the coordinates are in the sea or not.
version: 1.1.14
homepage: https://apiverve.com/marketplace/coordinatesaresea?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/coordinatesaresea-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
